# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'ask'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_ask_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="ask" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_ask_provider">')
    parts.append('provider *')
    parts.append('</label>')
    parts.append('<input name="provider" id="f_ask_provider" class="lf-input" required="required" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_ask_message">')
    parts.append('message *')
    parts.append('</label>')
    parts.append('<input name="message" id="f_ask_message" class="lf-input" required="required" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_ask_thread_id">')
    parts.append('thread_id')
    parts.append('</label>')
    parts.append('<input name="thread_id" id="f_ask_thread_id" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_ask_max_tokens">')
    parts.append('max_tokens')
    parts.append('</label>')
    parts.append('<input name="max_tokens" id="f_ask_max_tokens" class="lf-input" type="number">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_ask_rag_context">')
    parts.append('rag_context')
    parts.append('</label>')
    parts.append('<input name="rag_context" id="f_ask_rag_context" class="lf-checkbox" type="checkbox">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_ask_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_ask_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter ask')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
