# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'biblio'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_biblio_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="biblio" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_biblio_action">')
    parts.append('action *')
    parts.append('</label>')
    parts.append('<select name="action" id="f_biblio_action" class="lf-input" required="required">')
    parts.append('<option value="extract">')
    parts.append('extract')
    parts.append('</option>')
    parts.append('<option value="search">')
    parts.append('search')
    parts.append('</option>')
    parts.append('<option value="list">')
    parts.append('list')
    parts.append('</option>')
    parts.append('<option value="promote">')
    parts.append('promote')
    parts.append('</option>')
    parts.append('<option value="reject">')
    parts.append('reject')
    parts.append('</option>')
    parts.append('<option value="pin">')
    parts.append('pin')
    parts.append('</option>')
    parts.append('<option value="unpin">')
    parts.append('unpin')
    parts.append('</option>')
    parts.append('<option value="get">')
    parts.append('get')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_biblio_text">')
    parts.append('text')
    parts.append('</label>')
    parts.append('<textarea name="text" id="f_biblio_text" class="lf-input" rows="5">')
    parts.append('</textarea>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_biblio_idea_id">')
    parts.append('idea_id')
    parts.append('</label>')
    parts.append('<input name="idea_id" id="f_biblio_idea_id" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_biblio_entry_id">')
    parts.append('entry_id')
    parts.append('</label>')
    parts.append('<input name="entry_id" id="f_biblio_entry_id" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_biblio_reason">')
    parts.append('reason')
    parts.append('</label>')
    parts.append('<input name="reason" id="f_biblio_reason" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_biblio_status_filter">')
    parts.append('status_filter')
    parts.append('</label>')
    parts.append('<input name="status_filter" id="f_biblio_status_filter" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_biblio_limit">')
    parts.append('limit')
    parts.append('</label>')
    parts.append('<input name="limit" id="f_biblio_limit" class="lf-input" type="number">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_biblio_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_biblio_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter biblio')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
