# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'blackboard_propose_fact'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_blackboard_propose_fact_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="blackboard_propose_fact" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_blackboard_propose_fact_zone_name">')
    parts.append('zone_name *')
    parts.append('</label>')
    parts.append('<input name="zone_name" id="f_blackboard_propose_fact_zone_name" class="lf-input" required="required" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Zone cible')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_blackboard_propose_fact_fact">')
    parts.append('fact *')
    parts.append('</label>')
    parts.append('<input name="fact" id="f_blackboard_propose_fact_fact" class="lf-input" required="required" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Contenu du fait (texte ou JSON)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_blackboard_propose_fact_category">')
    parts.append('category')
    parts.append('</label>')
    parts.append('<input name="category" id="f_blackboard_propose_fact_category" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append("Classification (ex: 'api', 'bug', 'rule')")
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_blackboard_propose_fact_trust">')
    parts.append('trust')
    parts.append('</label>')
    parts.append('<input name="trust" id="f_blackboard_propose_fact_trust" class="lf-input" type="number" step="any">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Confiance [0.0-1.0], défaut 0.5')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_blackboard_propose_fact_key">')
    parts.append('key')
    parts.append('</label>')
    parts.append('<input name="key" id="f_blackboard_propose_fact_key" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Optionnel: clé explicite (sinon hash du fait)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_blackboard_propose_fact_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_blackboard_propose_fact_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter blackboard_propose_fact')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
