# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'cross_platform_fs'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_cross_platform_fs_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="cross_platform_fs" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_cross_platform_fs_action">')
    parts.append('action *')
    parts.append('</label>')
    parts.append('<select name="action" id="f_cross_platform_fs_action" class="lf-input" required="required">')
    parts.append('<option value="copy_to_docker">')
    parts.append('copy_to_docker')
    parts.append('</option>')
    parts.append('<option value="copy_from_docker">')
    parts.append('copy_from_docker')
    parts.append('</option>')
    parts.append('<option value="copy_to_wsl">')
    parts.append('copy_to_wsl')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_cross_platform_fs_src">')
    parts.append('src *')
    parts.append('</label>')
    parts.append('<input name="src" id="f_cross_platform_fs_src" class="lf-input" required="required" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Source path (host path or container:path)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_cross_platform_fs_dest">')
    parts.append('dest *')
    parts.append('</label>')
    parts.append('<input name="dest" id="f_cross_platform_fs_dest" class="lf-input" required="required" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Destination path (host path or container:path)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_cross_platform_fs_distro">')
    parts.append('distro')
    parts.append('</label>')
    parts.append('<input name="distro" id="f_cross_platform_fs_distro" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('WSL distro name (default Debian)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_cross_platform_fs_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_cross_platform_fs_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter cross_platform_fs')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
