# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'event'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_event_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="event" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_event_action">')
    parts.append('action *')
    parts.append('</label>')
    parts.append('<select name="action" id="f_event_action" class="lf-input" required="required">')
    parts.append('<option value="publish">')
    parts.append('publish')
    parts.append('</option>')
    parts.append('<option value="history">')
    parts.append('history')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_event_topic">')
    parts.append('topic')
    parts.append('</label>')
    parts.append('<input name="topic" id="f_event_topic" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_event_kind">')
    parts.append('kind')
    parts.append('</label>')
    parts.append('<input name="kind" id="f_event_kind" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_event_data">')
    parts.append('data')
    parts.append('</label>')
    parts.append('<textarea name="data" id="f_event_data" class="lf-input" rows="3" placeholder="JSON object">')
    parts.append('</textarea>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_event_topics">')
    parts.append('topics')
    parts.append('</label>')
    parts.append('<textarea name="topics" id="f_event_topics" class="lf-input" rows="3" placeholder="JSON array">')
    parts.append('</textarea>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_event_limit">')
    parts.append('limit')
    parts.append('</label>')
    parts.append('<input name="limit" id="f_event_limit" class="lf-input" type="number">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_event_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_event_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter event')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
