# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'forge_spawn_swarm'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_forge_spawn_swarm_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="forge_spawn_swarm" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_forge_spawn_swarm_tasks">')
    parts.append('tasks *')
    parts.append('</label>')
    parts.append('<textarea name="tasks" id="f_forge_spawn_swarm_tasks" class="lf-input" required="required" rows="3" placeholder="JSON array">')
    parts.append('</textarea>')
    parts.append('<small class="lf-field__hint">')
    parts.append('Sous-tâches du DAG (indépendantes ou liées par deps)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_forge_spawn_swarm_root">')
    parts.append('root')
    parts.append('</label>')
    parts.append('<input name="root" id="f_forge_spawn_swarm_root" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('racine projet (défaut: repo)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_forge_spawn_swarm_dry_run">')
    parts.append('dry_run')
    parts.append('</label>')
    parts.append('<input name="dry_run" id="f_forge_spawn_swarm_dry_run" class="lf-checkbox" type="checkbox">')
    parts.append('<small class="lf-field__hint">')
    parts.append('valide+exécute sans écrire le disque')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_forge_spawn_swarm_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_forge_spawn_swarm_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter forge_spawn_swarm')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
