# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'forge_trigger_audit'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_forge_trigger_audit_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="forge_trigger_audit" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_forge_trigger_audit_target_files">')
    parts.append('target_files *')
    parts.append('</label>')
    parts.append('<textarea name="target_files" id="f_forge_trigger_audit_target_files" class="lf-input" required="required" rows="3" placeholder="JSON array">')
    parts.append('</textarea>')
    parts.append('<small class="lf-field__hint">')
    parts.append('fichiers à auditer')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_forge_trigger_audit_lenses">')
    parts.append('lenses')
    parts.append('</label>')
    parts.append('<textarea name="lenses" id="f_forge_trigger_audit_lenses" class="lf-input" rows="3" placeholder="JSON array">')
    parts.append('</textarea>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_forge_trigger_audit_root">')
    parts.append('root')
    parts.append('</label>')
    parts.append('<input name="root" id="f_forge_trigger_audit_root" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('racine projet (défaut: repo)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_forge_trigger_audit_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_forge_trigger_audit_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter forge_trigger_audit')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
