# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'forge_deep_explore'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_forge_deep_explore_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="forge_deep_explore" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_forge_deep_explore_intent">')
    parts.append('intent *')
    parts.append('</label>')
    parts.append('<input name="intent" id="f_forge_deep_explore_intent" class="lf-input" required="required" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('What you want to understand (natural-language goal).')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_forge_deep_explore_target">')
    parts.append('target')
    parts.append('</label>')
    parts.append('<input name="target" id="f_forge_deep_explore_target" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Optional regex/keywords (| = OR) to focus the search.')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_forge_deep_explore_globs">')
    parts.append('globs')
    parts.append('</label>')
    parts.append('<input name="globs" id="f_forge_deep_explore_globs" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Optional comma globs (default app/forge_*.py,tools/*.py).')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_forge_deep_explore_breadth">')
    parts.append('breadth')
    parts.append('</label>')
    parts.append('<select name="breadth" id="f_forge_deep_explore_breadth" class="lf-input">')
    parts.append('<option value="narrow">')
    parts.append('narrow')
    parts.append('</option>')
    parts.append('<option value="medium">')
    parts.append('medium')
    parts.append('</option>')
    parts.append('<option value="wide">')
    parts.append('wide')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('<small class="lf-field__hint">')
    parts.append('Search breadth (default medium).')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_forge_deep_explore_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_forge_deep_explore_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter forge_deep_explore')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
