# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'governed_edit'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_governed_edit_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="governed_edit" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_governed_edit_path">')
    parts.append('path *')
    parts.append('</label>')
    parts.append('<input name="path" id="f_governed_edit_path" class="lf-input" required="required" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Chemin relatif au repo')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_governed_edit_content">')
    parts.append('content')
    parts.append('</label>')
    parts.append('<textarea name="content" id="f_governed_edit_content" class="lf-input" rows="5">')
    parts.append('</textarea>')
    parts.append('<small class="lf-field__hint">')
    parts.append('Contenu complet (mode write)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_governed_edit_blocks">')
    parts.append('blocks')
    parts.append('</label>')
    parts.append('<input name="blocks" id="f_governed_edit_blocks" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Blocs SEARCH/REPLACE (mode edition chirurgicale)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_governed_edit_allow_critical">')
    parts.append('allow_critical')
    parts.append('</label>')
    parts.append('<input name="allow_critical" id="f_governed_edit_allow_critical" class="lf-checkbox" type="checkbox">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Derogation owner pour un CRITICAL_FILE. Reservee au ring <= 1, tracee. Sans elle l autorisation owner n a aucun canal : la variable d env est celle du process h')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_governed_edit_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_governed_edit_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter governed_edit')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
