# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'graph_ppr'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_graph_ppr_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="graph_ppr" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_graph_ppr_seed">')
    parts.append('seed *')
    parts.append('</label>')
    parts.append('<input name="seed" id="f_graph_ppr_seed" class="lf-input" required="required" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Module de départ (seed PPR)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_graph_ppr_alpha">')
    parts.append('alpha')
    parts.append('</label>')
    parts.append('<input name="alpha" id="f_graph_ppr_alpha" class="lf-input" type="number" step="any">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Facteur de téléportation (défaut 0.85)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_graph_ppr_depth">')
    parts.append('depth')
    parts.append('</label>')
    parts.append('<input name="depth" id="f_graph_ppr_depth" class="lf-input" type="number">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Profondeur de construction du graphe (défaut 3)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_graph_ppr_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_graph_ppr_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter graph_ppr')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
