# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'graph_cve_propagate'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_graph_cve_propagate_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="graph_cve_propagate" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_graph_cve_propagate_cve_id">')
    parts.append('cve_id *')
    parts.append('</label>')
    parts.append('<input name="cve_id" id="f_graph_cve_propagate_cve_id" class="lf-input" required="required" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Identifiant CVE (ex: CVE-2025-1234)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_graph_cve_propagate_entry_module">')
    parts.append('entry_module *')
    parts.append('</label>')
    parts.append('<input name="entry_module" id="f_graph_cve_propagate_entry_module" class="lf-input" required="required" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append("Module d'entrée (point d'injection)")
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_graph_cve_propagate_max_depth">')
    parts.append('max_depth')
    parts.append('</label>')
    parts.append('<input name="max_depth" id="f_graph_cve_propagate_max_depth" class="lf-input" type="number">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Profondeur BFS max (défaut 3)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_graph_cve_propagate_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_graph_cve_propagate_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter graph_cve_propagate')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
