# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'graph_edge_score'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_graph_edge_score_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="graph_edge_score" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_graph_edge_score_src">')
    parts.append('src *')
    parts.append('</label>')
    parts.append('<input name="src" id="f_graph_edge_score_src" class="lf-input" required="required" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Module source (chemin ou nom)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_graph_edge_score_dst">')
    parts.append('dst *')
    parts.append('</label>')
    parts.append('<input name="dst" id="f_graph_edge_score_dst" class="lf-input" required="required" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Module destination')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_graph_edge_score_edge_type">')
    parts.append('edge_type')
    parts.append('</label>')
    parts.append('<select name="edge_type" id="f_graph_edge_score_edge_type" class="lf-input">')
    parts.append('<option value="import">')
    parts.append('import')
    parts.append('</option>')
    parts.append('<option value="call">')
    parts.append('call')
    parts.append('</option>')
    parts.append('<option value="inherit">')
    parts.append('inherit')
    parts.append('</option>')
    parts.append('<option value="embed_sim">')
    parts.append('embed_sim')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('<small class="lf-field__hint">')
    parts.append('Type de relation')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_graph_edge_score_metadata">')
    parts.append('metadata')
    parts.append('</label>')
    parts.append('<textarea name="metadata" id="f_graph_edge_score_metadata" class="lf-input" rows="3" placeholder="JSON object">')
    parts.append('</textarea>')
    parts.append('<small class="lf-field__hint">')
    parts.append('Optionnel: sim (float), deprecated (bool)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_graph_edge_score_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_graph_edge_score_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter graph_edge_score')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
