# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'hub'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_hub_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="hub" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_hub_action">')
    parts.append('action *')
    parts.append('</label>')
    parts.append('<select name="action" id="f_hub_action" class="lf-input" required="required">')
    parts.append('<option value="get_mode">')
    parts.append('get_mode')
    parts.append('</option>')
    parts.append('<option value="set_mode">')
    parts.append('set_mode')
    parts.append('</option>')
    parts.append('<option value="poll">')
    parts.append('poll')
    parts.append('</option>')
    parts.append('<option value="notify">')
    parts.append('notify')
    parts.append('</option>')
    parts.append('<option value="list_providers">')
    parts.append('list_providers')
    parts.append('</option>')
    parts.append('<option value="search_recent">')
    parts.append('search_recent')
    parts.append('</option>')
    parts.append('<option value="whoami">')
    parts.append('whoami')
    parts.append('</option>')
    parts.append('<option value="emit_telemetry">')
    parts.append('emit_telemetry')
    parts.append('</option>')
    parts.append('<option value="quota_model">')
    parts.append('quota_model')
    parts.append('</option>')
    parts.append('<option value="quota_report">')
    parts.append('quota_report')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_hub_mode">')
    parts.append('mode')
    parts.append('</label>')
    parts.append('<input name="mode" id="f_hub_mode" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_hub_message">')
    parts.append('message')
    parts.append('</label>')
    parts.append('<input name="message" id="f_hub_message" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_hub_to">')
    parts.append('to')
    parts.append('</label>')
    parts.append('<select name="to" id="f_hub_to" class="lf-input">')
    parts.append('<option value="claude">')
    parts.append('claude')
    parts.append('</option>')
    parts.append('<option value="gemini">')
    parts.append('gemini')
    parts.append('</option>')
    parts.append('<option value="cline">')
    parts.append('cline')
    parts.append('</option>')
    parts.append('<option value="daemon">')
    parts.append('daemon')
    parts.append('</option>')
    parts.append('<option value="hub">')
    parts.append('hub')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('<small class="lf-field__hint">')
    parts.append('Destinataire explicite pour action=notify')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_hub_topic">')
    parts.append('topic')
    parts.append('</label>')
    parts.append('<input name="topic" id="f_hub_topic" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_hub_limit">')
    parts.append('limit')
    parts.append('</label>')
    parts.append('<input name="limit" id="f_hub_limit" class="lf-input" type="number">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_hub_flash">')
    parts.append('flash')
    parts.append('</label>')
    parts.append('<input name="flash" id="f_hub_flash" class="lf-input" type="number" step="any">')
    parts.append('<small class="lf-field__hint">')
    parts.append('quota_report: % flash used')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_hub_flash_lite">')
    parts.append('flash_lite')
    parts.append('</label>')
    parts.append('<input name="flash_lite" id="f_hub_flash_lite" class="lf-input" type="number" step="any">')
    parts.append('<small class="lf-field__hint">')
    parts.append('quota_report: % flash_lite used')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_hub_pro">')
    parts.append('pro')
    parts.append('</label>')
    parts.append('<input name="pro" id="f_hub_pro" class="lf-input" type="number" step="any">')
    parts.append('<small class="lf-field__hint">')
    parts.append('quota_report: % pro used')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_hub_preview_pro">')
    parts.append('preview_pro')
    parts.append('</label>')
    parts.append('<input name="preview_pro" id="f_hub_preview_pro" class="lf-input" type="number" step="any">')
    parts.append('<small class="lf-field__hint">')
    parts.append('quota_report: % preview_pro used')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_hub_quality">')
    parts.append('quality')
    parts.append('</label>')
    parts.append('<input name="quality" id="f_hub_quality" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('quota_model: high|medium|low|ultra')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_hub_apply">')
    parts.append('apply')
    parts.append('</label>')
    parts.append('<input name="apply" id="f_hub_apply" class="lf-checkbox" type="checkbox">')
    parts.append('<small class="lf-field__hint">')
    parts.append('quota_model: apply model selection')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_hub_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_hub_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter hub')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
