# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'manage_forge_lifecycle'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_manage_forge_lifecycle_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="manage_forge_lifecycle" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_manage_forge_lifecycle_organ_name">')
    parts.append('organ_name *')
    parts.append('</label>')
    parts.append('<input name="organ_name" id="f_manage_forge_lifecycle_organ_name" class="lf-input" required="required" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_manage_forge_lifecycle_action">')
    parts.append('action *')
    parts.append('</label>')
    parts.append('<select name="action" id="f_manage_forge_lifecycle_action" class="lf-input" required="required">')
    parts.append('<option value="START">')
    parts.append('START')
    parts.append('</option>')
    parts.append('<option value="STOP">')
    parts.append('STOP')
    parts.append('</option>')
    parts.append('<option value="RESTART">')
    parts.append('RESTART')
    parts.append('</option>')
    parts.append('<option value="STATUS">')
    parts.append('STATUS')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_manage_forge_lifecycle_priority">')
    parts.append('priority')
    parts.append('</label>')
    parts.append('<select name="priority" id="f_manage_forge_lifecycle_priority" class="lf-input">')
    parts.append('<option value="LOW">')
    parts.append('LOW')
    parts.append('</option>')
    parts.append('<option value="NORMAL">')
    parts.append('NORMAL')
    parts.append('</option>')
    parts.append('<option value="HIGH">')
    parts.append('HIGH')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_manage_forge_lifecycle_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_manage_forge_lifecycle_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter manage_forge_lifecycle')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
