# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'netcfg'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_netcfg_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="netcfg" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_netcfg_action">')
    parts.append('action *')
    parts.append('</label>')
    parts.append('<select name="action" id="f_netcfg_action" class="lf-input" required="required">')
    parts.append('<option value="ping">')
    parts.append('ping')
    parts.append('</option>')
    parts.append('<option value="vendors">')
    parts.append('vendors')
    parts.append('</option>')
    parts.append('<option value="list_equipments">')
    parts.append('list_equipments')
    parts.append('</option>')
    parts.append('<option value="get_dashboard">')
    parts.append('get_dashboard')
    parts.append('</option>')
    parts.append('<option value="topology">')
    parts.append('topology')
    parts.append('</option>')
    parts.append('<option value="audit">')
    parts.append('audit')
    parts.append('</option>')
    parts.append('<option value="verify_chain">')
    parts.append('verify_chain')
    parts.append('</option>')
    parts.append('<option value="preview_deploy">')
    parts.append('preview_deploy')
    parts.append('</option>')
    parts.append('<option value="open_terminal">')
    parts.append('open_terminal')
    parts.append('</option>')
    parts.append('<option value="export_topology">')
    parts.append('export_topology')
    parts.append('</option>')
    parts.append('<option value="vendor_search">')
    parts.append('vendor_search')
    parts.append('</option>')
    parts.append('<option value="vendor_stats">')
    parts.append('vendor_stats')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_netcfg_shape_id">')
    parts.append('shape_id')
    parts.append('</label>')
    parts.append('<input name="shape_id" id="f_netcfg_shape_id" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('preview_deploy/open_terminal')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_netcfg_command">')
    parts.append('command')
    parts.append('</label>')
    parts.append('<textarea name="command" id="f_netcfg_command" class="lf-input" rows="5">')
    parts.append('</textarea>')
    parts.append('<small class="lf-field__hint">')
    parts.append('open_terminal')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_netcfg_wait_ms">')
    parts.append('wait_ms')
    parts.append('</label>')
    parts.append('<input name="wait_ms" id="f_netcfg_wait_ms" class="lf-input" type="number">')
    parts.append('<small class="lf-field__hint">')
    parts.append('open_terminal')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_netcfg_format">')
    parts.append('format')
    parts.append('</label>')
    parts.append('<select name="format" id="f_netcfg_format" class="lf-input">')
    parts.append('<option value="d2">')
    parts.append('d2')
    parts.append('</option>')
    parts.append('<option value="drawthe">')
    parts.append('drawthe')
    parts.append('</option>')
    parts.append('<option value="mermaid">')
    parts.append('mermaid')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('<small class="lf-field__hint">')
    parts.append('export_topology')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_netcfg_query">')
    parts.append('query')
    parts.append('</label>')
    parts.append('<input name="query" id="f_netcfg_query" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('vendor_search')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_netcfg_vendor">')
    parts.append('vendor')
    parts.append('</label>')
    parts.append('<input name="vendor" id="f_netcfg_vendor" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('vendor_search')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_netcfg_limit">')
    parts.append('limit')
    parts.append('</label>')
    parts.append('<input name="limit" id="f_netcfg_limit" class="lf-input" type="number">')
    parts.append('<small class="lf-field__hint">')
    parts.append('vendor_search')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_netcfg_db_path">')
    parts.append('db_path')
    parts.append('</label>')
    parts.append('<input name="db_path" id="f_netcfg_db_path" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('verify_chain')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_netcfg_scale_m_per_px">')
    parts.append('scale_m_per_px')
    parts.append('</label>')
    parts.append('<input name="scale_m_per_px" id="f_netcfg_scale_m_per_px" class="lf-input" type="number" step="any">')
    parts.append('<small class="lf-field__hint">')
    parts.append('topology')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_netcfg_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_netcfg_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter netcfg')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
