# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'nokido_ensure_service'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_nokido_ensure_service_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="nokido_ensure_service" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_nokido_ensure_service_service">')
    parts.append('service *')
    parts.append('</label>')
    parts.append('<input name="service" id="f_nokido_ensure_service_service" class="lf-input" required="required" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('docker | searxng | hub | ollama | netcfg | webhub | graph | embed | lmstudio (or a Nokido<Name>).')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_nokido_ensure_service_desired_state">')
    parts.append('desired_state')
    parts.append('</label>')
    parts.append('<select name="desired_state" id="f_nokido_ensure_service_desired_state" class="lf-input">')
    parts.append('<option value="running">')
    parts.append('running')
    parts.append('</option>')
    parts.append('<option value="stopped">')
    parts.append('stopped')
    parts.append('</option>')
    parts.append('<option value="restarted">')
    parts.append('restarted')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('<small class="lf-field__hint">')
    parts.append('Desired state (default running).')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_nokido_ensure_service_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_nokido_ensure_service_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter nokido_ensure_service')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
