# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'orchestrate'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_orchestrate_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="orchestrate" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_orchestrate_task">')
    parts.append('task *')
    parts.append('</label>')
    parts.append('<input name="task" id="f_orchestrate_task" class="lf-input" required="required" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Tâche à accomplir')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_orchestrate_tools">')
    parts.append('tools')
    parts.append('</label>')
    parts.append('<textarea name="tools" id="f_orchestrate_tools" class="lf-input" rows="3" placeholder="JSON array">')
    parts.append('</textarea>')
    parts.append('<small class="lf-field__hint">')
    parts.append('Noms des outils autorisés (vide = tous les outils du ring)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_orchestrate_max_iter">')
    parts.append('max_iter')
    parts.append('</label>')
    parts.append('<input name="max_iter" id="f_orchestrate_max_iter" class="lf-input" type="number">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Max itérations (défaut 10)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_orchestrate_model">')
    parts.append('model')
    parts.append('</label>')
    parts.append('<input name="model" id="f_orchestrate_model" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Modèle llama-server (défaut laforge-coder)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_orchestrate_temperature">')
    parts.append('temperature')
    parts.append('</label>')
    parts.append('<input name="temperature" id="f_orchestrate_temperature" class="lf-input" type="number" step="any">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Température (défaut 0.2)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_orchestrate_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_orchestrate_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter orchestrate')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
