# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'query'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_query_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="query" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_query_sql">')
    parts.append('sql')
    parts.append('</label>')
    parts.append('<input name="sql" id="f_query_sql" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_query_action">')
    parts.append('action')
    parts.append('</label>')
    parts.append('<select name="action" id="f_query_action" class="lf-input">')
    parts.append('<option value="schema">')
    parts.append('schema')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_query_table">')
    parts.append('table')
    parts.append('</label>')
    parts.append('<input name="table" id="f_query_table" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_query_db">')
    parts.append('db')
    parts.append('</label>')
    parts.append('<input name="db" id="f_query_db" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_query_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_query_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter query')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
