# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'rag'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_rag_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="rag" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_rag_action">')
    parts.append('action *')
    parts.append('</label>')
    parts.append('<select name="action" id="f_rag_action" class="lf-input" required="required">')
    parts.append('<option value="index">')
    parts.append('index')
    parts.append('</option>')
    parts.append('<option value="search">')
    parts.append('search')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_rag_task_id">')
    parts.append('task_id')
    parts.append('</label>')
    parts.append('<input name="task_id" id="f_rag_task_id" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_rag_result">')
    parts.append('result')
    parts.append('</label>')
    parts.append('<input name="result" id="f_rag_result" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_rag_topic">')
    parts.append('topic')
    parts.append('</label>')
    parts.append('<input name="topic" id="f_rag_topic" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_rag_limit">')
    parts.append('limit')
    parts.append('</label>')
    parts.append('<input name="limit" id="f_rag_limit" class="lf-input" type="number">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_rag_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_rag_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter rag')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
