# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'read'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_read_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="read" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_read_action">')
    parts.append('action *')
    parts.append('</label>')
    parts.append('<select name="action" id="f_read_action" class="lf-input" required="required">')
    parts.append('<option value="file">')
    parts.append('file')
    parts.append('</option>')
    parts.append('<option value="tail_logs">')
    parts.append('tail_logs')
    parts.append('</option>')
    parts.append('<option value="archived">')
    parts.append('archived')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_read_path">')
    parts.append('path')
    parts.append('</label>')
    parts.append('<input name="path" id="f_read_path" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_read_pattern">')
    parts.append('pattern')
    parts.append('</label>')
    parts.append('<input name="pattern" id="f_read_pattern" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_read_lines">')
    parts.append('lines')
    parts.append('</label>')
    parts.append('<input name="lines" id="f_read_lines" class="lf-input" type="number">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_read_id">')
    parts.append('id')
    parts.append('</label>')
    parts.append('<input name="id" id="f_read_id" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('CCR blob id (action=archived) — récupère une sortie stashée par le guard')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_read_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_read_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter read')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
