# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'research_agent'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_research_agent_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="research_agent" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_research_agent_objective">')
    parts.append('objective *')
    parts.append('</label>')
    parts.append('<input name="objective" id="f_research_agent_objective" class="lf-input" required="required" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_research_agent_max_rounds">')
    parts.append('max_rounds')
    parts.append('</label>')
    parts.append('<input name="max_rounds" id="f_research_agent_max_rounds" class="lf-input" type="number">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_research_agent_max_urls">')
    parts.append('max_urls')
    parts.append('</label>')
    parts.append('<input name="max_urls" id="f_research_agent_max_urls" class="lf-input" type="number">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_research_agent_domain">')
    parts.append('domain')
    parts.append('</label>')
    parts.append('<input name="domain" id="f_research_agent_domain" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_research_agent_provider">')
    parts.append('provider')
    parts.append('</label>')
    parts.append('<input name="provider" id="f_research_agent_provider" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_research_agent_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_research_agent_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter research_agent')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
