# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'run'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_run_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="run" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_action">')
    parts.append('action *')
    parts.append('</label>')
    parts.append('<select name="action" id="f_run_action" class="lf-input" required="required">')
    parts.append('<option value="github">')
    parts.append('github')
    parts.append('</option>')
    parts.append('<option value="python">')
    parts.append('python')
    parts.append('</option>')
    parts.append('<option value="shell">')
    parts.append('shell')
    parts.append('</option>')
    parts.append('<option value="trusted_script">')
    parts.append('trusted_script')
    parts.append('</option>')
    parts.append('<option value="atlas_build">')
    parts.append('atlas_build')
    parts.append('</option>')
    parts.append('<option value="save_situation">')
    parts.append('save_situation')
    parts.append('</option>')
    parts.append('<option value="atlas_get">')
    parts.append('atlas_get')
    parts.append('</option>')
    parts.append('<option value="make_snapshot">')
    parts.append('make_snapshot')
    parts.append('</option>')
    parts.append('<option value="setup_check">')
    parts.append('setup_check')
    parts.append('</option>')
    parts.append('<option value="restart_claude">')
    parts.append('restart_claude')
    parts.append('</option>')
    parts.append('<option value="audit_log">')
    parts.append('audit_log')
    parts.append('</option>')
    parts.append('<option value="worker_status">')
    parts.append('worker_status')
    parts.append('</option>')
    parts.append('<option value="run_job">')
    parts.append('run_job')
    parts.append('</option>')
    parts.append('<option value="job_status">')
    parts.append('job_status')
    parts.append('</option>')
    parts.append('<option value="job_kill">')
    parts.append('job_kill')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_code">')
    parts.append('code')
    parts.append('</label>')
    parts.append('<textarea name="code" id="f_run_code" class="lf-input" rows="5">')
    parts.append('</textarea>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_path">')
    parts.append('path')
    parts.append('</label>')
    parts.append('<input name="path" id="f_run_path" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Script path under tools/ or app/ (trusted_script action)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_script_args">')
    parts.append('script_args')
    parts.append('</label>')
    parts.append('<input name="script_args" id="f_run_script_args" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('CLI args for trusted_script (chaine style shell, parsee via shlex)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_script">')
    parts.append('script')
    parts.append('</label>')
    parts.append('<input name="script" id="f_run_script" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('run_job: chemin .py (sous C:/tmp ou racine Nokido) a lancer DETACHE')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_online">')
    parts.append('online')
    parts.append('</label>')
    parts.append('<input name="online" id="f_run_online" class="lf-checkbox" type="checkbox">')
    parts.append('<small class="lf-field__hint">')
    parts.append('run_job: sandbox-online (reseau sortant) si true, sinon offline')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_job_id">')
    parts.append('job_id')
    parts.append('</label>')
    parts.append('<input name="job_id" id="f_run_job_id" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('job_status/job_kill: id retourne par run_job (poll etat running|done|killed, rc, log_tail)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_force">')
    parts.append('force')
    parts.append('</label>')
    parts.append('<input name="force" id="f_run_force" class="lf-checkbox" type="checkbox">')
    parts.append('<small class="lf-field__hint">')
    parts.append('job_kill: accepte un python dont la cmdline est illisible (identification via la fiche du job seulement)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_notify_agent">')
    parts.append('notify_agent')
    parts.append('</label>')
    parts.append('<input name="notify_agent" id="f_run_notify_agent" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append("run_job: agent a notifier sur l'inbox a la fin du job (optionnel)")
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_lane">')
    parts.append('lane')
    parts.append('</label>')
    parts.append('<input name="lane" id="f_run_lane" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append("run_job: lane d'admission (ex 'gpu8091'). Si fournie et deja tenue -> refus REACTIF (anti-stacking/anti-wedge): 1 job lourd par lane, liberee a la fin. Cf forge")
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_rss_cap_mb">')
    parts.append('rss_cap_mb')
    parts.append('</label>')
    parts.append('<input name="rss_cap_mb" id="f_run_rss_cap_mb" class="lf-input" type="number">')
    parts.append('<small class="lf-field__hint">')
    parts.append('run_job: plafond memoire de l ARBRE du job, en Mo (defaut env LAFORGE_JOB_RSS_CAP_MB, sinon 6000). Depasse -> job TUE, rc=137, motif dans le .err. Borne la fami')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_commands">')
    parts.append('commands')
    parts.append('</label>')
    parts.append('<textarea name="commands" id="f_run_commands" class="lf-input" rows="3" placeholder="JSON array">')
    parts.append('</textarea>')
    parts.append('<small class="lf-field__hint">')
    parts.append('Parallel shell commands (shell action only)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_sandbox">')
    parts.append('sandbox')
    parts.append('</label>')
    parts.append('<select name="sandbox" id="f_run_sandbox" class="lf-input">')
    parts.append('<option value="local">')
    parts.append('local')
    parts.append('</option>')
    parts.append('<option value="docker">')
    parts.append('docker')
    parts.append('</option>')
    parts.append('<option value="ps_clm">')
    parts.append('ps_clm')
    parts.append('</option>')
    parts.append('<option value="windows">')
    parts.append('windows')
    parts.append('</option>')
    parts.append('<option value="wasm">')
    parts.append('wasm')
    parts.append('</option>')
    parts.append('<option value="console">')
    parts.append('console')
    parts.append('</option>')
    parts.append('<option value="gvisor">')
    parts.append('gvisor')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('<small class="lf-field__hint">')
    parts.append("TYPE de bac (default: local). N'EST PAS le levier d'egress -- pour le reseau sortant, utiliser `network`. Une valeur HORS de cet enum est REFUSEE (fail-closed) ")
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_network">')
    parts.append('network')
    parts.append('</label>')
    parts.append('<input name="network" id="f_run_network" class="lf-checkbox" type="checkbox">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Reseau SORTANT (actions shell et python). absent/false -> compte LaForgeSbxOffline (loopback seul, egress bloque) ; true -> LaForgeSbxOnline (egress autorise). ')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_container">')
    parts.append('container')
    parts.append('</label>')
    parts.append('<input name="container" id="f_run_container" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Docker container name (sandbox=docker)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_timeout">')
    parts.append('timeout')
    parts.append('</label>')
    parts.append('<input name="timeout" id="f_run_timeout" class="lf-input" type="number">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Per-command timeout seconds (default 30)')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_run_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_run_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter run')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
