# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'skill'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_skill_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="skill" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_skill_action">')
    parts.append('action *')
    parts.append('</label>')
    parts.append('<select name="action" id="f_skill_action" class="lf-input" required="required">')
    parts.append('<option value="list">')
    parts.append('list')
    parts.append('</option>')
    parts.append('<option value="load">')
    parts.append('load')
    parts.append('</option>')
    parts.append('<option value="search">')
    parts.append('search')
    parts.append('</option>')
    parts.append('<option value="ingest">')
    parts.append('ingest')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_skill_name">')
    parts.append('name')
    parts.append('</label>')
    parts.append('<input name="name" id="f_skill_name" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Nom du skill ex: forge-anatomy')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_skill_query">')
    parts.append('query')
    parts.append('</label>')
    parts.append('<input name="query" id="f_skill_query" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('Pour action=search')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_skill_limit">')
    parts.append('limit')
    parts.append('</label>')
    parts.append('<input name="limit" id="f_skill_limit" class="lf-input" type="number">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_skill_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_skill_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter skill')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
