# GÉNÉRÉ par forge_ui_sweep (moulinette déterministe, 0 token) — tool 'task'.
# Régén : run_job tools/forge_ui_sweep.py. Cible web_hub HTMX/Alpine/lf-.
from __future__ import annotations

def render_task_form():
    """Généré par forge_ui_moulinette (déterministe). Cible web_hub HTMX/Alpine/laforge-ds."""
    import html as _h
    _e = lambda v: _h.escape(str(v))
    parts = []
    parts.append('<form class="lf-form" data-tool="task" hx-post="/run" hx-swap="outerHTML">')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_task_action">')
    parts.append('action *')
    parts.append('</label>')
    parts.append('<select name="action" id="f_task_action" class="lf-input" required="required">')
    parts.append('<option value="assign">')
    parts.append('assign')
    parts.append('</option>')
    parts.append('<option value="claim">')
    parts.append('claim')
    parts.append('</option>')
    parts.append('<option value="result">')
    parts.append('result')
    parts.append('</option>')
    parts.append('<option value="status">')
    parts.append('status')
    parts.append('</option>')
    parts.append('</select>')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_task_task_id">')
    parts.append('task_id')
    parts.append('</label>')
    parts.append('<input name="task_id" id="f_task_task_id" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_task_job_id">')
    parts.append('job_id')
    parts.append('</label>')
    parts.append('<input name="job_id" id="f_task_job_id" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_task_description">')
    parts.append('description')
    parts.append('</label>')
    parts.append('<input name="description" id="f_task_description" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_task_agent">')
    parts.append('agent')
    parts.append('</label>')
    parts.append('<input name="agent" id="f_task_agent" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_task_intent">')
    parts.append('intent')
    parts.append('</label>')
    parts.append('<input name="intent" id="f_task_intent" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_task_priority">')
    parts.append('priority')
    parts.append('</label>')
    parts.append('<input name="priority" id="f_task_priority" class="lf-input" type="number">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_task_result">')
    parts.append('result')
    parts.append('</label>')
    parts.append('<input name="result" id="f_task_result" class="lf-input" type="text">')
    parts.append('</div>')
    parts.append('<div class="lf-field">')
    parts.append('<label class="lf-field__label" for="f_task_explanation">')
    parts.append('explanation')
    parts.append('</label>')
    parts.append('<input name="explanation" id="f_task_explanation" class="lf-input" type="text">')
    parts.append('<small class="lf-field__hint">')
    parts.append('One sentence explanation as to why this tool is being used, and how it contributes to the goal. Optional during transition (warn-only), required after 2026-08-0')
    parts.append('</small>')
    parts.append('</div>')
    parts.append('<button class="lf-btn lf-btn--primary" type="submit">')
    parts.append('Exécuter task')
    parts.append('</button>')
    parts.append('</form>')
    return ''.join(parts)
