"""
forge_ps_agent.py - Micro-Agents PowerShell avec déport cognitif
=================================================================
3 méthodes selon le document d'architecture :

M1 - Micro-Agent Ollama Edge
     Script PS contient sa propre boucle LLM locale (Ollama/llama-server)
     → analyse sur place, remonte seulement la conclusion

M2 - RAG Local Intégré
     Script PS vectorise les logs localement via Ollama embeddings
     → recherche sémantique sur l'hôte, extraction d'erreur pertinente

M3 - Déport d'Intention (Goal-Oriented)
     Script PS pré-compilé avec try/catch adaptatif
     → gère ses propres erreurs sans aller-retour Hub

Règle d'Or :
  - Tout payload LLM généré par le script déporté inclut les tools sandbox
  - Le CLM (N2) s'applique sur le container du script entier
  - La conclusion remontée est toujours structurée JSON

Usage :
    from forge_ps_agent import PSAgentBuilder
    script = PSAgentBuilder.build_edge_agent(
        intent="Analyser pourquoi le service NokidoMCP est lent",
        context={"service": "NokidoMCP", "port": 8766}
    )
    # Exécuter via ps_run
    result = mcp("ps_run", {"code": script, "mode": "CLM"})
"""

from __future__ import annotations
import json
import logging
import os
from pathlib import Path
from typing import Any

logger = logging.getLogger("Nokido.PSAgent")

ROOT = Path(__file__).resolve().parent.parent

# ── Config endpoints LLM disponibles ─────────────────────────────────────────
_OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434")
_OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL_DEFAULT", "qwen2.5-coder:1.5b")
_LLAMA_URL = os.environ.get("LLAMACPP_URL", "http://127.0.0.1:8090")
_HUB_URL = os.environ.get("HUB_URL", "http://127.0.0.1:8766")
_EMBED_MODEL = os.environ.get("OLLAMA_EMBEDDINGS_MODEL", "nomic-embed-text")


class PSAgentBuilder:
    """
    Générateur de scripts PowerShell micro-agents autonomes.
    Chaque script respecte la Règle d'Or : payload LLM validé + CLM compatible.
    """

    @staticmethod
    def build_edge_agent(
        intent: str,
        context: dict[str, Any] | None = None,
        llm_url: str = _OLLAMA_URL,
        llm_model: str = _OLLAMA_MODEL,
        max_tokens: int = 300,
    ) -> str:
        """
        M1 — Micro-Agent Ollama Edge.

        Génère un script PS qui :
        1. Collecte des données système (logs, process, réseau)
        2. Appelle le LLM local pour analyser
        3. Remonte seulement la conclusion JSON au Hub

        Args:
            intent    : L'intention en langage naturel (ex: "Pourquoi le service est lent ?")
            context   : Variables contextuelles (service, port, path...)
            llm_url   : URL du LLM local (Ollama ou llama-server)
            llm_model : Modèle à utiliser
            max_tokens: Limite tokens pour la réponse LLM
        """
        ctx_json = json.dumps(context or {}, ensure_ascii=False)
        # Validation payload LLM (Règle d'Or) -- tools sandbox inclus
        tools_def = json.dumps(
            [
                {
                    "type": "function",
                    "function": {
                        "name": "report_conclusion",
                        "description": "Remonte la conclusion d'analyse au Hub",
                        "parameters": {
                            "type": "object",
                            "properties": {
                                "status": {"type": "string", "enum": ["ok", "warning", "critical", "unknown"]},
                                "conclusion": {"type": "string", "maxLength": 500},
                                "action": {"type": "string", "enum": ["none", "restart", "alert", "investigate"]},
                            },
                            "required": ["status", "conclusion", "action"],
                        },
                    },
                }
            ]
        )

        script = f'''\
# Nokido MicroAgent M1 — Edge LLM Analysis
# Intent: {intent}
# Generated by PSAgentBuilder — CLM compatible

$ErrorActionPreference = "Stop"
$LLM_URL   = "{llm_url}/api/chat"
$LLM_MODEL = "{llm_model}"
$MAX_TOKENS = {max_tokens}
$CTX = '{ctx_json}' | ConvertFrom-Json

function Invoke-LocalLLM {{
    param([string]$Prompt, [string]$SystemPrompt = "Tu es un expert ops. Réponds en JSON structuré uniquement.")
    
    # Règle d'Or : payload validé avec contraintes sandbox
    $payload = @{{
        model    = $LLM_MODEL
        messages = @(
            @{{ role = "system"; content = $SystemPrompt }},
            @{{ role = "user";   content = $Prompt }}
        )
        stream    = $false
        options   = @{{ num_predict = $MAX_TOKENS; temperature = 0.1 }}
    }} | ConvertTo-Json -Depth 5 -Compress

    try {{
        $response = Invoke-RestMethod -Uri $LLM_URL -Method Post `
            -ContentType "application/json" -Body $payload -TimeoutSec 30
        return $response.message.content
    }} catch {{
        return '{{"status":"unknown","conclusion":"LLM inaccessible: $($_.Exception.Message)","action":"none"}}'
    }}
}}

function Get-SystemDiagnostics {{
    # Collecte locale — uniquement des lectures (CLM compatible)
    $diag = @{{}}

    # Processes
    try {{
        $procs = Get-Process | Sort-Object CPU -Descending |
            Select-Object -First 5 |
            ForEach-Object {{ "$($_.Name):$([math]::Round($_.CPU,1))s" }}
        $diag.top_processes = $procs -join ", "
    }} catch {{ $diag.top_processes = "unavailable" }}

    # Réseau
    try {{
        $conns = (Get-NetTCPConnection -State Established -EA 0 | Measure-Object).Count
        $diag.tcp_connections = $conns
    }} catch {{ $diag.tcp_connections = -1 }}

    # Service Nokido si dans le contexte
    if ($CTX.service) {{
        try {{
            $svc = Get-Service -Name $CTX.service -EA 0
            $diag.service_status = if ($svc) {{ $svc.Status.ToString() }} else {{ "not_found" }}
        }} catch {{ $diag.service_status = "error" }}
    }}

    # Port si dans le contexte
    if ($CTX.port) {{
        $listening = (Get-NetTCPConnection -LocalPort $CTX.port -State Listen -EA 0 | Measure-Object).Count
        $diag.port_listening = $listening -gt 0
    }}

    return $diag | ConvertTo-Json -Compress
}}

# ── Main Agent Loop ─────────────────────────────────────────────────────────
try {{
    # 1. Collecte
    $diagnostics = Get-SystemDiagnostics

    # 2. Analyse LLM locale
    $prompt = @"
Intent: {intent}
Context: $($CTX | ConvertTo-Json -Compress)
Diagnostics: $diagnostics

Analyse et réponds UNIQUEMENT avec ce JSON (pas de markdown) :
{{"status":"ok|warning|critical|unknown","conclusion":"<max 200 chars>","action":"none|restart|alert|investigate"}}
"@

    $raw = Invoke-LocalLLM -Prompt $prompt

    # 3. Valider + parser la réponse (Règle d'Or : sortie structurée)
    $json = $null
    try {{
        # Extraire le JSON si la réponse contient du texte autour
        if ($raw -match '\\{{.*\\}}') {{
            $json = $Matches[0] | ConvertFrom-Json
        }}
    }} catch {{}}

    if ($null -eq $json) {{
        $json = @{{ status="unknown"; conclusion="Parse error: $($raw.Substring(0,[Math]::Min(100,$raw.Length)))"; action="investigate" }}
    }}

    # 4. Remonte SEULEMENT la conclusion au Hub (pas les logs bruts)
    $result = @{{
        agent    = "M1_EdgeLLM"
        intent   = "{intent}"
        status   = $json.status
        conclusion = $json.conclusion
        action   = $json.action
        model    = $LLM_MODEL
    }} | ConvertTo-Json -Compress

    Write-Output $result

}} catch {{
    # Auto-gestion d'erreur — pas d'aller-retour Hub
    @{{
        agent="M1_EdgeLLM"; intent="{intent}";
        status="critical"; conclusion="Agent error: $($_.Exception.Message.Substring(0,[Math]::Min(150,$_.Exception.Message.Length)))";
        action="investigate"; model=$LLM_MODEL
    }} | ConvertTo-Json -Compress | Write-Output
}}
'''
        return script

    @staticmethod
    def build_rag_agent(
        log_path: str,
        search_query: str,
        embed_model: str = _EMBED_MODEL,
        max_lines: int = 500,
    ) -> str:
        """
        M2 — RAG Local Intégré.

        Génère un script PS qui :
        1. Lit un fichier de log localement
        2. Vectorise via Ollama embeddings
        3. Fait la recherche sémantique sur place (cosine simple)
        4. Remonte les lignes pertinentes + contexte

        Args:
            log_path    : Chemin du fichier log à analyser
            search_query: La requête sémantique (ex: "erreur mémoire service")
            embed_model : Modèle d'embedding Ollama
            max_lines   : Limite de lignes à traiter
        """
        script = f'''\
# Nokido MicroAgent M2 — Local RAG Log Analysis
# Query: {search_query}
# Log: {log_path}

$ErrorActionPreference = "Continue"
$EMBED_URL   = "{_OLLAMA_URL}/api/embed"
$EMBED_MODEL = "{embed_model}"
$LOG_PATH    = "{log_path}"
$QUERY       = "{search_query}"
$MAX_LINES   = {max_lines}
$TOP_K       = 5

function Get-Embedding {{
    param([string]$Text)
    $payload = @{{
        model = $EMBED_MODEL
        input = $Text.Substring(0, [Math]::Min(512, $Text.Length))
    }} | ConvertTo-Json -Compress
    try {{
        $r = Invoke-RestMethod -Uri $EMBED_URL -Method Post `
            -ContentType "application/json" -Body $payload -TimeoutSec 15
        return $r.embeddings[0]
    }} catch {{
        return $null
    }}
}}

function Get-CosineSimilarity {{
    param([double[]]$A, [double[]]$B)
    if ($null -eq $A -or $null -eq $B -or $A.Length -ne $B.Length) {{ return 0.0 }}
    $dot  = 0.0; $na = 0.0; $nb = 0.0
    for ($i = 0; $i -lt $A.Length; $i++) {{
        $dot += $A[$i] * $B[$i]
        $na  += $A[$i] * $A[$i]
        $nb  += $B[$i] * $B[$i]
    }}
    $denom = [Math]::Sqrt($na) * [Math]::Sqrt($nb)
    return if ($denom -gt 0) {{ $dot / $denom }} else {{ 0.0 }}
}}

try {{
    # 1. Lire le log
    if (-not (Test-Path $LOG_PATH)) {{
        @{{ status="error"; conclusion="Log not found: $LOG_PATH"; matches=@() }} |
            ConvertTo-Json -Compress | Write-Output
        exit 0
    }}
    $lines = Get-Content $LOG_PATH -Tail $MAX_LINES -EA 0
    if (-not $lines) {{
        @{{ status="empty"; conclusion="Log vide ou illisible"; matches=@() }} |
            ConvertTo-Json -Compress | Write-Output
        exit 0
    }}

    # 2. Vectoriser la requête
    $queryVec = Get-Embedding -Text $QUERY
    if ($null -eq $queryVec) {{
        # Fallback : grep simple si embeddings indisponibles
        $matches = $lines | Where-Object {{ $_ -match [regex]::Escape($QUERY.Split()[0]) }} |
            Select-Object -First $TOP_K
        @{{ status="fallback_grep"; conclusion="Embeddings indisponibles, grep utilisé";
            matches=$matches }} | ConvertTo-Json -Compress | Write-Output
        exit 0
    }}

    # 3. Vectoriser + scorer les lignes (batch par 10)
    $scored = @()
    for ($i = 0; $i -lt $lines.Count; $i += 10) {{
        $batch = $lines[$i..[Math]::Min($i+9, $lines.Count-1)]
        foreach ($line in $batch) {{
            if ($line.Trim().Length -lt 10) {{ continue }}
            $vec = Get-Embedding -Text $line
            if ($vec) {{
                $score = Get-CosineSimilarity -A $queryVec -B $vec
                $scored += @{{ line=$line; score=$score }}
            }}
        }}
    }}

    # 4. Top-K résultats
    $topK = $scored | Sort-Object {{ $_.score }} -Descending |
        Select-Object -First $TOP_K

    $result = @{{
        agent   = "M2_LocalRAG"
        query   = $QUERY
        log     = $LOG_PATH
        lines_analyzed = $lines.Count
        status  = if ($topK.Count -gt 0) {{ "ok" }} else {{ "no_match" }}
        matches = $topK | ForEach-Object {{ @{{ score=[Math]::Round($_.score,3); line=$_.line }} }}
    }} | ConvertTo-Json -Depth 4 -Compress

    Write-Output $result

}} catch {{
    @{{ agent="M2_LocalRAG"; status="error";
        conclusion=$_.Exception.Message.Substring(0,[Math]::Min(200,$_.Exception.Message.Length)) }} |
        ConvertTo-Json -Compress | Write-Output
}}
'''
        return script

    @staticmethod
    def build_intention_agent(
        intention: str,
        steps: list[dict],
        hub_report_url: str = f"{_HUB_URL}/mcp",
    ) -> str:
        """
        M3 — Déport d'Intention (Goal-Oriented).

        Génère un script PS pré-compilé avec :
        - Gestion d'erreur adaptative (try/catch avec fallback)
        - Pas d'aller-retour Hub entre les étapes
        - Rapport final structuré uniquement

        Args:
            intention : L'objectif global (ex: "S'assurer que NokidoMCP est UP")
            steps     : Liste d'étapes avec fallbacks
                        [{"name": "...", "cmd": "...", "fallback": "...", "critical": bool}]
        """
        steps_ps = []
        for i, step in enumerate(steps):
            name = step.get("name", f"step_{i}")
            cmd = step.get("cmd", "")
            fallback = step.get("fallback", "")
            critical = str(step.get("critical", False)).lower()

            step_block = f'''\
    # Step {i + 1}: {name}
    $stepName = "{name}"
    try {{
        $stepResult = ({cmd})
        $results += @{{ step=$stepName; status="ok"; output=[string]$stepResult }}
        $log += "[OK] $stepName"
    }} catch {{
        $log += "[FAIL] $stepName : $($_.Exception.Message.Substring(0,[Math]::Min(80,$_.Exception.Message.Length)))"
        if ("{critical}" -eq "true") {{
            $results += @{{ step=$stepName; status="critical"; error=$_.Exception.Message }}
            $criticalFailure = $true
        }} else {{
            # Fallback automatique -- pas d'aller-retour Hub
            try {{
                $fbResult = ({fallback if fallback else "Write-Output 'skipped'"})
                $results += @{{ step=$stepName; status="fallback"; output=[string]$fbResult }}
                $log += "[FALLBACK] $stepName OK"
            }} catch {{
                $results += @{{ step=$stepName; status="failed"; error=$_.Exception.Message }}
            }}
        }}
    }}'''
            steps_ps.append(step_block)

        steps_code = "\n".join(steps_ps)

        script = f'''\
# Nokido MicroAgent M3 — Goal-Oriented Execution
# Intention: {intention}

$ErrorActionPreference = "Continue"
$results = @()
$log     = @()
$criticalFailure = $false
$startTime = Get-Date

{steps_code}

# Rapport final -- remontée unique au Hub
$elapsed = [Math]::Round(((Get-Date) - $startTime).TotalSeconds, 2)
$status  = if ($criticalFailure) {{ "critical" }}
           elseif ($results | Where-Object {{ $_.status -eq "failed" }}) {{ "warning" }}
           else {{ "ok" }}

@{{
    agent     = "M3_GoalOriented"
    intention = "{intention}"
    status    = $status
    elapsed_s = $elapsed
    steps     = $results
    log       = $log -join " | "
    critical_failure = $criticalFailure
}} | ConvertTo-Json -Depth 4 -Compress | Write-Output
'''
        return script

    @staticmethod
    def build_diagnostic_agent(
        service: str = "NokidoMCP",
        port: int = 8766,
    ) -> str:
        """
        Agent de diagnostic complet combinant M1+M3.
        Vérifie l'état d'un service Nokido et propose une action.
        Prêt à l'emploi, pas de configuration requise.
        """
        steps = [
            {
                "name": "check_port",
                "cmd": f"(Get-NetTCPConnection -LocalPort {port} -State Listen -EA 0 | Measure-Object).Count -gt 0",
                "fallback": "$false",
                "critical": False,
            },
            {
                "name": "check_service",
                "cmd": f'(Get-Service -Name "{service}" -EA 0).Status',
                "fallback": '"not_found"',
                "critical": False,
            },
            {
                "name": "check_memory_mb",
                "cmd": '[Math]::Round((Get-Process | Where-Object {$_.ProcessName -like "*python*"} | Measure-Object WorkingSet -Sum).Sum / 1MB, 0)',
                "fallback": "-1",
                "critical": False,
            },
            {
                "name": "hub_health",
                "cmd": f'(Invoke-RestMethod "http://127.0.0.1:{port}/health" -TimeoutSec 3).status',
                "fallback": '"unreachable"',
                "critical": True,
            },
        ]
        base_script = PSAgentBuilder.build_intention_agent(
            intention=f"Diagnostiquer {service} sur port {port}",
            steps=steps,
        )
        # Ajouter analyse LLM edge après le diagnostic M3
        edge_addition = f'''

# M1 Edge Analysis sur les résultats M3
$diagSummary = $results | ConvertTo-Json -Compress
$llmPrompt = "Service: {service} port:{port}. Diagnostics: $diagSummary. Réponds UNIQUEMENT JSON: {{status,conclusion,action}}"

$llmPayload = @{{
    model    = "{_OLLAMA_MODEL}"
    messages = @(@{{ role="user"; content=$llmPrompt }})
    stream   = $false
    options  = @{{ num_predict=150; temperature=0.1 }}
}} | ConvertTo-Json -Depth 4 -Compress

try {{
    $llmResp = Invoke-RestMethod -Uri "{_OLLAMA_URL}/api/chat" -Method Post `
        -ContentType "application/json" -Body $llmPayload -TimeoutSec 20
    $analysis = $llmResp.message.content
}} catch {{
    $analysis = '{{"status":"unknown","conclusion":"LLM offline","action":"none"}}'
}}

@{{
    agent      = "M1+M3_Diagnostic"
    service    = "{service}"
    port       = {port}
    m3_status  = $status
    m3_steps   = $results.Count
    llm_analysis = $analysis
    elapsed_s  = $elapsed
}} | ConvertTo-Json -Depth 4 -Compress | Write-Output
'''
        # Retirer le dernier Write-Output du script M3 et ajouter M1
        base_script = base_script.rsplit("| Write-Output", 1)[0] + "\n" + edge_addition
        return base_script


# ── Tool MCP : ps_agent ───────────────────────────────────────────────────────


def build_agent_for_mcp(agent_type: str, args: dict) -> str:
    """
    Point d'entrée pour handle_ps_agent dans forge_mcp_registry.
    Génère le script selon le type demandé.
    """
    if agent_type == "edge":
        return PSAgentBuilder.build_edge_agent(
            intent=args.get("intent", "Diagnostiquer le système"),
            context=args.get("context", {}),
            llm_model=args.get("model", _OLLAMA_MODEL),
        )
    elif agent_type == "rag":
        return PSAgentBuilder.build_rag_agent(
            log_path=args.get("log_path", "logs/mcp_service_err.log"),
            search_query=args.get("query", "erreur critique"),
        )
    elif agent_type == "goal":
        return PSAgentBuilder.build_intention_agent(
            intention=args.get("intention", "Vérifier le système"),
            steps=args.get("steps", []),
        )
    elif agent_type == "diagnostic":
        return PSAgentBuilder.build_diagnostic_agent(
            service=args.get("service", "NokidoMCP"),
            port=int(args.get("port", 8766)),
        )
    raise ValueError(f"agent_type inconnu: {agent_type}")


if __name__ == "__main__":
    # Test : générer et afficher le script de diagnostic
    print("=== Agent M1+M3 Diagnostic ===\n")
    script = PSAgentBuilder.build_diagnostic_agent()
    print(script[:800])
    print(f"\n... ({len(script)} chars total)")
