#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "laforge-webhub-poc"
version = "0.1.0"
description = "PoC of a single route served in a WASM component (WASI 0.2 / wasm32-wasip2)"

[[trigger.http]]
route = "/health"
component = "health-poc"

[component.health-poc]
source = "target/wasm32-wasip2/release/health_poc.wasm"
allowed_outbound_hosts = []

[component.health-poc.build]
command = "cargo build --target wasm32-wasip2 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
