"""
tools/gemini_oauth_refresh.py — Refresh Google OAuth token for Gemini CLI
Generated by Groq Llama-3.3-70B, corrected by Claude.
Reads ~/.gemini/oauth_creds.json, POSTs to Google token endpoint, writes back.
"""

import json
import os
import pathlib
import socket
import time
from datetime import UTC, datetime

import requests

# --- amorce namespace (point d'entree) : `sys.path[0]` vaut le dossier du
# script, pas la racine du depot. Sans cette ligne, `from nokido_agent...`
# leve ModuleNotFoundError quand ce fichier est lance par chemin.
import sys as _sys_amorce
from pathlib import Path as _Path_amorce
_RACINE_AMORCE = str(_Path_amorce(__file__).resolve().parent.parent)
if _RACINE_AMORCE not in _sys_amorce.path:
    _sys_amorce.path.insert(0, _RACINE_AMORCE)


def _nokido_running() -> bool:
    """True si hub :8766 répond (Nokido lancé)."""
    try:
        with socket.create_connection(("127.0.0.1", 8766), timeout=1):
            return True
    except OSError:
        return False


CREDS_PATH = pathlib.Path.home() / ".gemini" / "oauth_creds.json"
TOKEN_URL = "https://oauth2.googleapis.com/token"


# Client creds from env (set GEMINI_CLIENT_ID / GEMINI_CLIENT_SECRET in Nokido.env)
# or from the vault via forge_secrets. These are the Gemini CLI installed-app
# credentials -- public OAuth client (no real secret in installed-app flow per
# RFC 8252) but still scrubbed from source for cleanliness.
def _get(key: str, fallback: str = "") -> str:
    val = os.environ.get(key)
    if val:
        return val
    try:
        import sys as _sys
        from pathlib import Path as _P

        _sys.path.insert(0, str(_P(__file__).resolve().parent.parent / "app"))
        from nokido_agent.app.forge_secrets import get_secret  # noqa: PLC0415

        v = get_secret(key)
        if v:
            return v
    except Exception:
        pass
    return fallback


CLIENT_ID = _get("GEMINI_CLIENT_ID", "<set GEMINI_CLIENT_ID in vault or env>")
CLIENT_SECRET = _get("GEMINI_CLIENT_SECRET", "<set GEMINI_CLIENT_SECRET in vault or env>")


def refresh():
    if not CREDS_PATH.exists():
        print(f"[ERR] {CREDS_PATH} introuvable — relancer: gemini auth")
        return False

    creds = json.loads(CREDS_PATH.read_text())
    refresh_token = creds.get("refresh_token")
    if not refresh_token:
        print("[ERR] refresh_token absent dans oauth_creds.json")
        return False

    resp = requests.post(
        TOKEN_URL,
        data={
            "grant_type": "refresh_token",
            "refresh_token": refresh_token,
            "client_id": CLIENT_ID,
            "client_secret": CLIENT_SECRET,
        },
        timeout=10,
    )

    if not resp.ok:
        print(f"[ERR] {resp.status_code}: {resp.text[:300]}")
        return False

    data = resp.json()
    new_access = data["access_token"]
    expires_in = data.get("expires_in", 3600)
    expiry_ms = int(time.time() * 1000) + expires_in * 1000
    expiry_dt = datetime.fromtimestamp(expiry_ms / 1000, tz=UTC)

    creds["access_token"] = new_access
    creds["expiry_date"] = expiry_ms
    CREDS_PATH.write_text(json.dumps(creds, indent=2))

    print(f"[OK] access_token: {new_access[:60]}...")
    print(f"[OK] expiry: {expiry_dt.strftime('%Y-%m-%d %H:%M:%S UTC')} (+{expires_in}s)")
    return True


if __name__ == "__main__":
    if not _nokido_running():
        exit(0)  # Nokido pas lancé — skip silencieux
    ok = refresh()
    exit(0 if ok else 1)
