# nssm_setup_services.ps1 — generated by Groq Llama-3.3-70B, corrected by Claude
# Goal: Nokido services survive reboots (auto-start)
# Run as Administrator

$ErrorActionPreference = 'Continue'
$WorkDir = '$env:USERPROFILE\Script python IA\Nokido'
$PyExe   = '$env:USERPROFILE\miniforge3\python.exe'
$LogDir  = "$WorkDir\logs"

if (!(Test-Path $LogDir)) { New-Item -ItemType Directory -Path $LogDir | Out-Null }

# ── 1. CREATE NokidoBrainWorker if missing ──────────────────────────────────
if (!(Get-Service 'NokidoBrainWorker' -ErrorAction SilentlyContinue)) {
    Write-Host '[+] Install NokidoBrainWorker'
    nssm install NokidoBrainWorker $PyExe
    nssm set NokidoBrainWorker AppParameters    'app/brain_worker.py'
    nssm set NokidoBrainWorker AppDirectory     $WorkDir
    nssm set NokidoBrainWorker AppEnvironmentExtra 'TOKENIZERS_PARALLELISM=false' 'OMP_NUM_THREADS=1' 'MKL_NUM_THREADS=1' 'OPENBLAS_NUM_THREADS=1'
    nssm set NokidoBrainWorker AppStdout        "$LogDir\brain_worker.log"
    nssm set NokidoBrainWorker AppStderr        "$LogDir\brain_worker_err.log"
    nssm set NokidoBrainWorker AppStdoutCreationDisposition 4
    nssm set NokidoBrainWorker AppStderrCreationDisposition 4
    nssm set NokidoBrainWorker Start            SERVICE_AUTO_START
    nssm set NokidoBrainWorker DependOnService  NokidoMCP
    Write-Host '[+] NokidoBrainWorker installe'
} else {
    Write-Host '[=] NokidoBrainWorker existe deja'
}

# ── 2. SET Automatic startup on existing services ───────────────────────────
foreach ($svc in @('NokidoMCP', 'NokidoGeminiDaemon', 'NokidoAutonomousLoops', 'NokidoWatchdog')) {
    if (Get-Service $svc -ErrorAction SilentlyContinue) {
        nssm set $svc Start SERVICE_AUTO_START
        Write-Host "[~] $svc -> Automatic"
    } else {
        Write-Host "[!] $svc absent - skip"
    }
}

# ── 3. Start stopped services (skip NokidoMCP — already running manually) ──
foreach ($svc in @('NokidoBrainWorker', 'NokidoGeminiDaemon')) {
    $s = Get-Service $svc -ErrorAction SilentlyContinue
    if ($s -and $s.Status -ne 'Running') {
        Write-Host "[>] Start $svc"
        nssm start $svc
        Start-Sleep -Seconds 3
        $s.Refresh()
        Write-Host "    -> $($s.Status)"
    } elseif ($s) {
        Write-Host "[=] $svc deja Running"
    }
}

# ── 4. Final status ──────────────────────────────────────────────────────────
Write-Host ''
Write-Host '=== STATUS FINAL ==='
foreach ($svc in @('NokidoMCP', 'NokidoBrainWorker', 'NokidoGeminiDaemon', 'NokidoAutonomousLoops', 'NokidoWatchdog')) {
    $status = nssm status $svc 2>$null
    Write-Host "  $svc : $status"
}
