# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeCode(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodeAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeCode", llm_response=llm_response, mode="request")
        return typing.cast(types.CodeAnalysis, __result__)

    def ExtractAdrDecision(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AdrExtract:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAdrDecision", llm_response=llm_response, mode="request")
        return typing.cast(types.AdrExtract, __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, __result__)

    def ExtractSpec(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SpecExtract:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractSpec", llm_response=llm_response, mode="request")
        return typing.cast(types.SpecExtract, __result__)

    def ExtractStyle(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.StyleExtract:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractStyle", llm_response=llm_response, mode="request")
        return typing.cast(types.StyleExtract, __result__)

    def IndexMarkdownDocs(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.MdDocSummary"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="IndexMarkdownDocs", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.MdDocSummary"], __result__)

    def RouteQueryToDocs(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RouterDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RouteQueryToDocs", llm_response=llm_response, mode="request")
        return typing.cast(types.RouterDecision, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeCode(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodeAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeCode", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodeAnalysis, __result__)

    def ExtractAdrDecision(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AdrExtract:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAdrDecision", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AdrExtract, __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, __result__)

    def ExtractSpec(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SpecExtract:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractSpec", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SpecExtract, __result__)

    def ExtractStyle(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.StyleExtract:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractStyle", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.StyleExtract, __result__)

    def IndexMarkdownDocs(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.MdDocSummary"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="IndexMarkdownDocs", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.MdDocSummary"], __result__)

    def RouteQueryToDocs(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RouterDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RouteQueryToDocs", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RouterDecision, __result__)

    