# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (8)
# #########################################################################

class AdrExtract(BaseModel):
    id: typing.Optional[int] = Field(default=None, description='ADR sequential id if numbered (e.g. ADR-002 → 2)')
    title: typing.Optional[str] = None
    status: typing.Optional[typing.Union[typing_extensions.Literal['draft'], typing_extensions.Literal['accepted'], typing_extensions.Literal['planned'], typing_extensions.Literal['rejected'], typing_extensions.Literal['superseded'], typing_extensions.Literal['deprecated']]] = None
    context_one_line: typing.Optional[str] = Field(default=None, description='One sentence — what problem motivated this ADR')
    decision: typing.Optional[str] = Field(default=None, description='The actual decision in 1-3 sentences. No history, no debate, just what was decided.')
    constraints: typing.List[str] = Field(description='Hard constraints/requirements derived from the decision (max 5)')
    invalidates_if: typing.Optional[str] = Field(default=None, description='Condition under which this decision becomes obsolete')
    source_path: typing.Optional[str] = None

class CodeAnalysis(BaseModel):
    language: typing.Optional[str] = Field(default=None, description='Programming language detected')
    complexity_score: typing.Optional[int] = Field(default=None, description='Cyclomatic complexity 1-100')
    issues: typing.List["Issue"]
    suggestions: typing.List[str]
    refactor_priority: typing.Optional[typing.Union[typing_extensions.Literal['low'], typing_extensions.Literal['medium'], typing_extensions.Literal['high'], typing_extensions.Literal['critical']]] = None

class Issue(BaseModel):
    line: typing.Optional[int] = None
    severity: typing.Optional[typing.Union[typing_extensions.Literal['info'], typing_extensions.Literal['warning'], typing_extensions.Literal['error']]] = None
    category: typing.Optional[typing.Union[typing_extensions.Literal['security'], typing_extensions.Literal['performance'], typing_extensions.Literal['style'], typing_extensions.Literal['logic']]] = None
    message: typing.Optional[str] = None
    fix_hint: typing.Optional[str] = None

class MdDocSummary(BaseModel):
    path: typing.Optional[str] = Field(default=None, description='Relative path of the Markdown file')
    doc_type: typing.Optional[typing.Union[typing_extensions.Literal['adr'], typing_extensions.Literal['spec'], typing_extensions.Literal['style'], typing_extensions.Literal['guide'], typing_extensions.Literal['incident'], typing_extensions.Literal['roadmap'], typing_extensions.Literal['skill'], typing_extensions.Literal['other']]] = None
    title: typing.Optional[str] = Field(default=None, description='First H1 or file basename')
    status: typing.Optional[typing.Union[typing_extensions.Literal['draft'], typing_extensions.Literal['accepted'], typing_extensions.Literal['planned'], typing_extensions.Literal['rejected'], typing_extensions.Literal['superseded'], typing_extensions.Literal['deprecated'], typing_extensions.Literal['active'], typing_extensions.Literal['unknown']]] = None
    topics: typing.List[str] = Field(description='3-7 short keyword tags extracted from title + first paragraph')

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class RouterDecision(BaseModel):
    query: typing.Optional[str] = None
    selected_paths: typing.List[str] = Field(description='Relative paths of MD files relevant to query, ranked. Max 3.')
    rationale: typing.Optional[str] = Field(default=None, description='One short sentence : why these were chosen.')
    confidence: typing.Optional[float] = Field(default=None, description='0.0-1.0')

class SpecExtract(BaseModel):
    title: typing.Optional[str] = None
    endpoints: typing.List[str] = Field(description='API endpoints, ports, URLs mentioned (max 10)')
    data_types: typing.List[str] = Field(description='Key types/schemas referenced')
    rules: typing.List[str] = Field(description='Hard rules (MUST/SHALL) extracted from spec, max 8')
    source_path: typing.Optional[str] = None

class StyleExtract(BaseModel):
    naming_convention: typing.Optional[typing.Union[typing_extensions.Literal['camelCase'], typing_extensions.Literal['snake_case'], typing_extensions.Literal['kebab-case'], typing_extensions.Literal['PascalCase'], typing_extensions.Literal['mixed'], typing_extensions.Literal['unspecified']]] = None
    forbidden_libraries: typing.List[str]
    mandatory_patterns: typing.List[str] = Field(description='Coding patterns the doc requires (max 5)')
    forbidden_patterns: typing.List[str] = Field(description='Patterns the doc forbids (max 5)')
    source_path: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
