# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def AnalyzeCode(self, code: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.CodeAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.AnalyzeCode(code=code,context=context,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyzeCode", args={
                "code": code,"context": context,
            })
            return typing.cast(types.CodeAnalysis, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractAdrDecision(self, adr_content: str,adr_path: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AdrExtract:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractAdrDecision(adr_content=adr_content,adr_path=adr_path,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractAdrDecision", args={
                "adr_content": adr_content,"adr_path": adr_path,
            })
            return typing.cast(types.AdrExtract, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractResume(resume=resume,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractResume", args={
                "resume": resume,
            })
            return typing.cast(types.Resume, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractSpec(self, spec_content: str,spec_path: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SpecExtract:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractSpec(spec_content=spec_content,spec_path=spec_path,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractSpec", args={
                "spec_content": spec_content,"spec_path": spec_path,
            })
            return typing.cast(types.SpecExtract, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractStyle(self, style_content: str,style_path: str,
        baml_options: BamlCallOptions = {},
    ) -> types.StyleExtract:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractStyle(style_content=style_content,style_path=style_path,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractStyle", args={
                "style_content": style_content,"style_path": style_path,
            })
            return typing.cast(types.StyleExtract, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def IndexMarkdownDocs(self, doc_previews: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.MdDocSummary"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.IndexMarkdownDocs(doc_previews=doc_previews,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="IndexMarkdownDocs", args={
                "doc_previews": doc_previews,
            })
            return typing.cast(typing.List["types.MdDocSummary"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def RouteQueryToDocs(self, user_query: str,doc_index: typing.List["types.MdDocSummary"],
        baml_options: BamlCallOptions = {},
    ) -> types.RouterDecision:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.RouteQueryToDocs(user_query=user_query,doc_index=doc_index,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="RouteQueryToDocs", args={
                "user_query": user_query,"doc_index": doc_index,
            })
            return typing.cast(types.RouterDecision, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeCode(self, code: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CodeAnalysis, types.CodeAnalysis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyzeCode", args={
            "code": code,"context": context,
        })
        return baml_py.BamlSyncStream[stream_types.CodeAnalysis, types.CodeAnalysis](
          __result__,
          lambda x: typing.cast(stream_types.CodeAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CodeAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractAdrDecision(self, adr_content: str,adr_path: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AdrExtract, types.AdrExtract]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractAdrDecision", args={
            "adr_content": adr_content,"adr_path": adr_path,
        })
        return baml_py.BamlSyncStream[stream_types.AdrExtract, types.AdrExtract](
          __result__,
          lambda x: typing.cast(stream_types.AdrExtract, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AdrExtract, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Resume, types.Resume]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractResume", args={
            "resume": resume,
        })
        return baml_py.BamlSyncStream[stream_types.Resume, types.Resume](
          __result__,
          lambda x: typing.cast(stream_types.Resume, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractSpec(self, spec_content: str,spec_path: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.SpecExtract, types.SpecExtract]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractSpec", args={
            "spec_content": spec_content,"spec_path": spec_path,
        })
        return baml_py.BamlSyncStream[stream_types.SpecExtract, types.SpecExtract](
          __result__,
          lambda x: typing.cast(stream_types.SpecExtract, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SpecExtract, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractStyle(self, style_content: str,style_path: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.StyleExtract, types.StyleExtract]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractStyle", args={
            "style_content": style_content,"style_path": style_path,
        })
        return baml_py.BamlSyncStream[stream_types.StyleExtract, types.StyleExtract](
          __result__,
          lambda x: typing.cast(stream_types.StyleExtract, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.StyleExtract, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def IndexMarkdownDocs(self, doc_previews: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.MdDocSummary"], typing.List["types.MdDocSummary"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="IndexMarkdownDocs", args={
            "doc_previews": doc_previews,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.MdDocSummary"], typing.List["types.MdDocSummary"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.MdDocSummary"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.MdDocSummary"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def RouteQueryToDocs(self, user_query: str,doc_index: typing.List["types.MdDocSummary"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.RouterDecision, types.RouterDecision]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="RouteQueryToDocs", args={
            "user_query": user_query,"doc_index": doc_index,
        })
        return baml_py.BamlSyncStream[stream_types.RouterDecision, types.RouterDecision](
          __result__,
          lambda x: typing.cast(stream_types.RouterDecision, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RouterDecision, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeCode(self, code: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeCode", args={
            "code": code,"context": context,
        }, mode="request")
        return __result__
    def ExtractAdrDecision(self, adr_content: str,adr_path: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAdrDecision", args={
            "adr_content": adr_content,"adr_path": adr_path,
        }, mode="request")
        return __result__
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="request")
        return __result__
    def ExtractSpec(self, spec_content: str,spec_path: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractSpec", args={
            "spec_content": spec_content,"spec_path": spec_path,
        }, mode="request")
        return __result__
    def ExtractStyle(self, style_content: str,style_path: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractStyle", args={
            "style_content": style_content,"style_path": style_path,
        }, mode="request")
        return __result__
    def IndexMarkdownDocs(self, doc_previews: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="IndexMarkdownDocs", args={
            "doc_previews": doc_previews,
        }, mode="request")
        return __result__
    def RouteQueryToDocs(self, user_query: str,doc_index: typing.List["types.MdDocSummary"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RouteQueryToDocs", args={
            "user_query": user_query,"doc_index": doc_index,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeCode(self, code: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeCode", args={
            "code": code,"context": context,
        }, mode="stream")
        return __result__
    def ExtractAdrDecision(self, adr_content: str,adr_path: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAdrDecision", args={
            "adr_content": adr_content,"adr_path": adr_path,
        }, mode="stream")
        return __result__
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="stream")
        return __result__
    def ExtractSpec(self, spec_content: str,spec_path: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractSpec", args={
            "spec_content": spec_content,"spec_path": spec_path,
        }, mode="stream")
        return __result__
    def ExtractStyle(self, style_content: str,style_path: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractStyle", args={
            "style_content": style_content,"style_path": style_path,
        }, mode="stream")
        return __result__
    def IndexMarkdownDocs(self, doc_previews: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="IndexMarkdownDocs", args={
            "doc_previews": doc_previews,
        }, mode="stream")
        return __result__
    def RouteQueryToDocs(self, user_query: str,doc_index: typing.List["types.MdDocSummary"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RouteQueryToDocs", args={
            "user_query": user_query,"doc_index": doc_index,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))