# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (8)
# #########################################################################

class AdrExtract(BaseModel):
    id: typing.Optional[int] = Field(default=None, description='ADR sequential id if numbered (e.g. ADR-002 → 2)')
    title: str
    status: typing.Union[typing_extensions.Literal['draft'], typing_extensions.Literal['accepted'], typing_extensions.Literal['planned'], typing_extensions.Literal['rejected'], typing_extensions.Literal['superseded'], typing_extensions.Literal['deprecated']]
    context_one_line: str = Field(description='One sentence — what problem motivated this ADR')
    decision: str = Field(description='The actual decision in 1-3 sentences. No history, no debate, just what was decided.')
    constraints: typing.List[str] = Field(description='Hard constraints/requirements derived from the decision (max 5)')
    invalidates_if: typing.Optional[str] = Field(default=None, description='Condition under which this decision becomes obsolete')
    source_path: str

class CodeAnalysis(BaseModel):
    language: str = Field(description='Programming language detected')
    complexity_score: int = Field(description='Cyclomatic complexity 1-100')
    issues: typing.List["Issue"]
    suggestions: typing.List[str]
    refactor_priority: typing.Union[typing_extensions.Literal['low'], typing_extensions.Literal['medium'], typing_extensions.Literal['high'], typing_extensions.Literal['critical']]

class Issue(BaseModel):
    line: int
    severity: typing.Union[typing_extensions.Literal['info'], typing_extensions.Literal['warning'], typing_extensions.Literal['error']]
    category: typing.Union[typing_extensions.Literal['security'], typing_extensions.Literal['performance'], typing_extensions.Literal['style'], typing_extensions.Literal['logic']]
    message: str
    fix_hint: typing.Optional[str] = None

class MdDocSummary(BaseModel):
    path: str = Field(description='Relative path of the Markdown file')
    doc_type: typing.Union[typing_extensions.Literal['adr'], typing_extensions.Literal['spec'], typing_extensions.Literal['style'], typing_extensions.Literal['guide'], typing_extensions.Literal['incident'], typing_extensions.Literal['roadmap'], typing_extensions.Literal['skill'], typing_extensions.Literal['other']]
    title: str = Field(description='First H1 or file basename')
    status: typing.Union[typing_extensions.Literal['draft'], typing_extensions.Literal['accepted'], typing_extensions.Literal['planned'], typing_extensions.Literal['rejected'], typing_extensions.Literal['superseded'], typing_extensions.Literal['deprecated'], typing_extensions.Literal['active'], typing_extensions.Literal['unknown']]
    topics: typing.List[str] = Field(description='3-7 short keyword tags extracted from title + first paragraph')

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

class RouterDecision(BaseModel):
    query: str
    selected_paths: typing.List[str] = Field(description='Relative paths of MD files relevant to query, ranked. Max 3.')
    rationale: str = Field(description='One short sentence : why these were chosen.')
    confidence: float = Field(description='0.0-1.0')

class SpecExtract(BaseModel):
    title: str
    endpoints: typing.List[str] = Field(description='API endpoints, ports, URLs mentioned (max 10)')
    data_types: typing.List[str] = Field(description='Key types/schemas referenced')
    rules: typing.List[str] = Field(description='Hard rules (MUST/SHALL) extracted from spec, max 8')
    source_path: str

class StyleExtract(BaseModel):
    naming_convention: typing.Union[typing_extensions.Literal['camelCase'], typing_extensions.Literal['snake_case'], typing_extensions.Literal['kebab-case'], typing_extensions.Literal['PascalCase'], typing_extensions.Literal['mixed'], typing_extensions.Literal['unspecified']]
    forbidden_libraries: typing.List[str]
    mandatory_patterns: typing.List[str] = Field(description='Coding patterns the doc requires (max 5)')
    forbidden_patterns: typing.List[str] = Field(description='Patterns the doc forbids (max 5)')
    source_path: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
