# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AdrExtract": types.AdrExtract,
    "stream_types.AdrExtract": stream_types.AdrExtract,

    "types.CodeAnalysis": types.CodeAnalysis,
    "stream_types.CodeAnalysis": stream_types.CodeAnalysis,

    "types.Issue": types.Issue,
    "stream_types.Issue": stream_types.Issue,

    "types.MdDocSummary": types.MdDocSummary,
    "stream_types.MdDocSummary": stream_types.MdDocSummary,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.RouterDecision": types.RouterDecision,
    "stream_types.RouterDecision": stream_types.RouterDecision,

    "types.SpecExtract": types.SpecExtract,
    "stream_types.SpecExtract": stream_types.SpecExtract,

    "types.StyleExtract": types.StyleExtract,
    "stream_types.StyleExtract": stream_types.StyleExtract,


}